package app.gamenative.service.itch

import android.content.Context
import app.gamenative.PrefManager
import java.io.File
import java.nio.file.Paths

/**
 * itch.io API endpoints and install-path conventions.
 *
 * Auth is the user's own personal API key (Bearer token), generated by the
 * user themselves at https://itch.io/user/settings under "API Keys" --
 * droidtop/gamenative never creates an account or a key on the user's
 * behalf, only stores the key the user typed into a settings row.
 *
 * **Documented, official endpoints** (https://itch.io/docs/api/serverside):
 * - `GET /profile` (scope `profile:me`) -- verifies the key and returns the
 *   signed-in user.
 * - `GET /profile/owned-keys` (scope `profile:owned`) -- every download key
 *   the user holds (purchases, claims, bundles, gifts), each naming its
 *   game.
 *
 * **Undocumented but stable, reverse-engineered endpoints** -- itch's own
 * public API reference has no path to list a game's uploads or resolve a
 * real download URL for one (confirmed against both the current and the
 * "legacy" serverside API reference pages, 2026-09-27); the official itch
 * app and `butler` use private endpoints for this. The two used here are
 * the same ones the open-source downloader itch-dl relies on
 * (https://github.com/DragoonAethis/itch-dl, `itch_dl/downloader.py`):
 * - `GET /games/{game_id}/uploads?download_key_id={key}` -- the uploads
 *   (platform builds) for one owned game.
 * - `GET /uploads/{upload_id}/download?download_key_id={key}` -- resolves
 *   to JSON carrying the real, time-limited download URL for that upload.
 *
 * Because these two are not part of itch's documented contract they could
 * change without notice; [ItchApiClient] treats a shape it does not
 * recognise as a failure to sync rather than a crash, same as every other
 * store service here.
 */
object ItchConstants {
    private var appContext: Context? = null

    fun init(context: Context) {
        appContext = context.applicationContext
    }

    const val ITCH_API_BASE = "https://api.itch.io"

    val internalItchGamesPath: String
        get() {
            val context = appContext ?: throw IllegalStateException("ItchConstants not initialized. Call init() first.")
            val path = Paths.get(context.dataDir.path, "Itch", "games", "common").toString()
            File(path).mkdirs()
            return path
        }

    val externalItchGamesPath: String
        get() {
            val path = Paths.get(PrefManager.externalStoragePath, "Itch", "games", "common").toString()
            File(path).mkdirs()
            return path
        }

    val defaultItchGamesPath: String
        get() = if (PrefManager.useExternalStorage && File(PrefManager.externalStoragePath).exists()) {
            externalItchGamesPath
        } else {
            internalItchGamesPath
        }

    fun getGameInstallPath(gameTitle: String): String {
        val sanitized = gameTitle.replace(Regex("[^a-zA-Z0-9 ]"), "").trim().ifEmpty { "itch-game" }
        return Paths.get(defaultItchGamesPath, sanitized).toString()
    }

    /** Where the user's raw API key file lives, mirroring [app.gamenative.service.gog.GOGAuthManager]. */
    fun getAuthConfigPath(context: Context): String = "${context.filesDir}/itch_auth.json"
}
